# Generated by Django 2.2.4 on 2019-09-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, default='defaultPetPic.png', upload_to='pet_image'),
        ),
    ]
